### ISSUE TITLE
chore(a11y): re-run aXe reporting on all pages and re-test with VoiceOver/NVDA. 

### ISSUE THREAD

**Issue by miclgael** [miclgael/issues.michaelgale.dev#4]
## Context

A lot of areas of the site have changed since removing `pico.css` as a dependency, and a lot of new features have been added. There is still no automated test suite for a11y in place, so time to re-test. 

## Tasks

1. Install aXe dev tools

- [x] https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-GB

2. Run report on key pages

- [x] Home
- [x] Blog
- [x] Blog Single
- [x] Privacy
- [x] Contact
- [x] Uses
- [x] Tags
- [x] Projects
- [x] Notes

3. Make any required state-changes and run again

- [x] Home
- [x] Blog
- [x] Blog Single
- [x] Privacy
- [x] Contact
- [x] Uses
- [x] Tags
- [x] Projects
- [x] Notes

3. Run report on Dark-mode

- [x] Home
- [x] Blog
- [x] Blog Single
- [x] Privacy
- [x] Contact
- [x] Uses
- [x] Tags
- [x] Projects
- [x] Notes

4. Capture results as new issues.

**Comment by miclgael** [comment]
Work planned for 24 Dec, 2023 - 7 Dec, 2023.

**Comment by miclgael** [comment]
- [x] Home: miclgael/issues#5 
- [x] Blog: #6
- [x] Blog single: https://github.com/miclgael/issues/issues/9
- [x] Projects: https://github.com/miclgael/issues/issues/7
- [x] Privacy: rediscovered #5 and provided another patch to deku-ui.
- [x] Tags: https://github.com/miclgael/issues/issues/10

**Comment by miclgael** [comment]
Blog: #6

**Comment by miclgael** [comment]
Projects: https://github.com/miclgael/issues/issues/7
